### ISSUE TITLE
Objetivos para este año

### ISSUE THREAD

**Issue by eafelix** [banode/organizadores#1]
Como apertura , esta bueno empezar a discutir los objetivos para este año, tanto de banode y nodeschool. Cuando digo objetivos, me refiero a los clásicos como: 

-con que frecuencia vamos a reunirnos para las charlas 
-búsqueda de lugares
-búsqueda de patrocinadores
-esquema de reuniones
-organización 
-organizacion en conjunto con otras comunidades (HIPER IMPORTANTE a mi punto de vista).

Ya @a0viedo  estuvo detrás de varios temas, charlándolo con todos , sobre todo el de la organización horizontal del grupo,
Esta bueno bajarlo acá ya de primera mano para promover este tipo de organización. No quiero que se pierda ninguna opinion ya que todos son tan autores de esto como nosotros y sus ideas, criticas, puntos de vista es muy importante.

**Comment by a0viedo** [comment]
Excelente @eafelix. Me queda pendiente escribir CONTRIBUTING.md, dónde hablaría acerca de la estructura horizontal y el hecho de que cualquiera que contribuya puede ser organizador. El último item, lo de las comunidades también lo estoy tratando de encarar por ejemplo para que no haya asperezas con **Node.js Argentina**. Una cosa que quería aclarar es que desde mi parte les voy a brindar la ayuda que necesiten en organizar, proponer charlas, etc. No estamos compitiendo con nadie, o al menos esa no es mi idea. Lo que también me interesa ver si con BANode podemos generar más participación de la comunidad y que realmente se sientan parte.

Sobre el resto de los puntos hasta ahora no tuve ningún avance, en particular con la búsqueda de un lugar fijo y con la búsqueda de sponsors (a esta última le dediqué casi una medida de tiempo despreciable).

Alguien que quiera proponer objetivos para lo que queda del año?
