### ISSUE TITLE
Idea de abrir un foro

### ISSUE THREAD

**Issue by eafelix** [banode/organizadores#10]
El titulo lo dice todo, un foro para subir contenidos, las charlas, documentation, reviews, noticias. 
Ideas :P 
Me imagino un lugar para crear contenido en nuestro idioma , y a medida que hacemos nuestros trabajos del dia a dia de descubrimiento, investigación y resolución, subirlo en este sitio con todo lo beneficioso que implica el hecho. Opinones :P

**Comment by andreslozadamosto** [comment]
Buenas, creo q un foro no es lo ideal. 

Podemos crear otro espacio en github para compartir las charlas (diapositivas hechas con reveal.js por ejemplo), codigos de los meetups y demas.

Por otro lado, se puede generar tb un proyecto en github en donde cada pregunta sea un issue y luego se sube el codigo para resolverlo y demas y asi se va armando un indice con las preguntas. Ademas creo q haber visto un blog q toma los post desde github (tengo q buscarlo) entonces, si se hace todo desde aca queda todo junto y se puede evitar q se pregunte 1000 veces lo mismo en el foro. Por experiencia propia (ya q he sido admisitrador en foros de programacion) nu foro no es lo mejor... 

Pero bueno, no se que opinaran ustedes...

**Comment by a0viedo** [comment]
+1 a no hacer un foro. nada nos impide poner eso que decís @eafelix en github, para eso tenemos los repos, espero que vayamos encontrando la forma de ordenarnos e ir metiendo contenido. tal cual se está haciendo en [iojs-es](https://github.com/iojs/iojs-es).

**Comment by eafelix** [comment]
Genial , la idea no era tanto de foro, sino proponer crear una fuente de recursos, me gusto mucho su feedback. Como se imaginan este centro de recursos en github, o bajo otra forma de que no sea foro?

**Comment by a0viedo** [comment]
depende a qué llames recursos. el readme.md puede ser un índice de lo que vos quieras, recordemos que hasta libros se escriben en github. sobre cada repo pondría una recopilación de datos más relevantes, por ejemplo en **charlas** podríamos hacer un historial de charlas con links a quienes las dieron más slides etc. en **organizadores**, cómo ayudar, qué necesitamos para cada meetup, etc. en **miembros** pondría media, cómo fotos de los eventos, feedback de las personas que fueron, qué otras meetups interesantes hay.

**Comment by andreslozadamosto** [comment]
Me parece bien esa organizacion, al menos por ahora... luego con el paso del tiempo seguro q se va puliendo
