### ISSUE TITLE
Agregar labels copados

### ISSUE THREAD

**Issue by a0viedo** [banode/organizadores#4]
Algunos que vienen por default no aplicarían, cómo _bug_ o _wontfix_. Sugerencias?

**Comment by a0viedo** [comment]
Pongansen creativos...

**Comment by pazguille** [comment]
Buenas, tiro algunos tags que se me ocurren respecto a los temas que pueden que pueden surgir:
- `charla`
- `feedback`
- `sponsor`

Si les parece que aplican los agrego :)

**Comment by eafelix** [comment]
Ufa yo use los default y me los borraste @a0viedo , cuando te vea hay tabla :neckbeard: jajajajjajajajajajajajaj
Me gusta los que recomienda @pazguille y ademas sumaria estos: 
-   sugerencia 
-  planificación
