### ISSUE TITLE
Definir primer fecha y debatir frecuencia de las meetups

### ISSUE THREAD

**Issue by eafelix** [banode/organizadores#8]
La idea es discutir lo que nos da el titulo del issue. 
Me gustaría escuchar propuestas y fundamentos a ellas para poder discutirlas entre todos.

**Comment by a0viedo** [comment]
- Frecuencia: por lo menos a mi me gustaría que sea mensual.
- Primer fecha: dado que ya tenemos [una charla](https://github.com/banode/charlas/issues/5) y otra que   Gorka mencionó, nos falta sólo un lugar. Marzo tal vez?

**Comment by pazguille** [comment]
Frecuencia: Me parece bien que sea mensual, igual depende mucho de poder conseguir speakers y venue, con lo que puede variar.

Primer fecha: Revisemos en meetup.com para verificar fechas. Nos pasó que BAFrontend y WordPress elegimos la misma fecha para Marzo :(

Venue: Estuve hablando con Martín de Areatres para hacer las BAFrontend y me ofreció un lugar con capacidad de 50 personas. Si te parece, @a0viedo te paso el contacto para que lo puedas contactar.

**Comment by eafelix** [comment]
Gracias @pazguille , nosotros vamos estar en su evento proximo, así charlamos de todo esto.

**Comment by eafelix** [comment]
Me gustaría que mas opinaran, pero por lo pronto concordamos en la frecuencia sea MENSUAL.
Voy a crear un documento manifiesto de objetivos de la org e info para los que quieran sumarse o simplemente disfrutar las charlas.

**Comment by hugoruscitti** [comment]
Por mí está perfecta la frecuencia mensual. En otros eventos vi que agregan un espacio para "lighting talks" (2 o 3 charlas de 5 minutos informales para animar a la gente). Vi que funciona bastante bien, por ahí podemos ensayar algo de eso también no?

**Comment by eafelix** [comment]
Si, eso va ir seguro, nosotros lo pudimos ver en Meetupjs y funciona muy bien

**Comment by a0viedo** [comment]
@hugoruscitti si lo tenía en mente, y si me olvidé de escribirlo en algún lado! me gusta dar espacio para lightning talks porque pueden ser más distendidas y en una de esas la gente se anima más fácil

**Comment by pazguille** [comment]
+1 Me gusta la idea de las "lighting talks" para promover el ser speaker. Mucha gente le tiene miedo o piensa que hay que ser saber mucho, lo cual no es así.

**Comment by andreslozadamosto** [comment]
Buenas!
Me parece perfecto que sea mensual, ademas todos participamos y vamos a otros meetup por lo que una reunion mensual me parece perfecto.

**Comment by eafelix** [comment]
Creo que no hay mucho mas que hablar de este tema por ahora,  el issue llega con esta conclusión: 
- Sera una reunion mensual. 
- Dos charlas de 30 minutos con espacio a lighting talk. 

Si les parece bien, cierro el issue?

**Comment by a0viedo** [comment]
si, creo que pudimos llegar a un consenso entre todos con respecto a lo más importante: **frecuencia de las meetups**. la primer fecha ya también está _casi_ confirmada (faltaría una charla)...
